package com.usermanagement.model;

/**
 * Represents a User entity with properties corresponding to the users table in the database.
 * <p>
 * This class is a simple POJO (Plain Old Java Object) that encapsulates
 * user details such as id, name, email, and country.
 * It provides constructors for creating new instances and standard getter/setter methods.
 * </p>
 * <p>
 * The {@code id} field uniquely identifies a user and is typically managed by the database.
 * </p>
 * 
 * <p><b>Usage example:</b></p>
 * <pre>
 *     User newUser = new User("Alice", "alice@example.com", "USA");
 *     User existingUser = new User(1, "Bob", "bob@example.com", "Canada");
 * </pre>
 * 
 * @author 
 * @version 1.0
 */
public class User {

    /**
     * Unique identifier for the user.
     * Typically auto-generated by the database upon insertion.
     */
    private int id;

    /**
     * Full name of the user.
     */
    private String name;

    /**
     * Email address of the user.
     */
    private String email;

    /**
     * Country associated with the user.
     */
    private String country;

    /**
     * Constructs a new User instance without an id.
     * Typically used when creating a new user before it is persisted.
     *
     * @param name    the user's full name
     * @param email   the user's email address
     * @param country the user's country
     */
    public User(String name, String email, String country) {
        super();
        this.name = name;
        this.email = email;
        this.country = country;
    }

    /**
     * Constructs a User instance with all fields specified.
     * Typically used when retrieving existing user data from a database.
     *
     * @param id      unique identifier of the user
     * @param name    the user's full name
     * @param email   the user's email address
     * @param country the user's country
     */
    public User(int id, String name, String email, String country) {
        super();
        this.id = id;
        this.name = name;
        this.email = email;
        this.country = country;
    }

    /**
     * Returns the user's unique identifier.
     *
     * @return the user id
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the user's unique identifier.
     * Usually managed by the persistence layer or database.
     *
     * @param id the user id to set
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Returns the user's full name.
     *
     * @return the user's name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the user's full name.
     *
     * @param name the user's name to set
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Returns the user's email address.
     *
     * @return the user's email
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the user's email address.
     *
     * @param email the user's email to set
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Returns the user's country.
     *
     * @return the user's country
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the user's country.
     *
     * @param country the user's country to set
     */
    public void setCountry(String country) {
        this.country = country;
    }
}
