package com.usermanagement.dao;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import java.util.ArrayList;
import java.util.List;

import com.usermanagement.model.User;

/**
 * <p>
 * Data Access Object (DAO) responsible for CRUD operations on the {@link User} entity.
 * This class encapsulates all database interactions related to the "users" table.
 * It manages connection handling, SQL execution, and result mapping.
 * </p>
 * 
 * <p>
 * <b>Connection Management:</b> Uses JDBC DriverManager for establishing connections. 
 * The {@link #getConnection()} method loads the MySQL JDBC driver explicitly for
 * backward compatibility. Connections are opened and closed automatically using
 * try-with-resources blocks to ensure proper resource management and prevent leaks.
 * </p>
 * 
 * <p>
 * <b>SQL Operations:</b> Uses prepared statements with parameter binding to protect
 * against SQL injection attacks. Queries are parameterized for safe execution.
 * </p>
 * 
 * <p>
 * <b>Transaction Handling:</b> Each CRUD method operates within its own auto-commit
 * transaction boundary by default. For multi-step transactions, external transaction
 * management is recommended (e.g., via a service layer).
 * </p>
 * 
 * <p>
 * <b>Exception Handling:</b> SQLExceptions are caught and logged (stack trace printed),
 * but not rethrown. For production, consider using a logging framework and
 * rethrowing as a custom unchecked exception to allow caller handling.
 * </p>
 * 
 * <p>
 * <b>Thread Safety:</b> This DAO class does not maintain any mutable shared state and
 * is thus thread-safe for concurrent use by multiple threads.
 * </p>
 *
 * @author  
 * @version 1.0
 * @see User
 */
public class UserDAO {

    /** JDBC URL for the MySQL database connection */
    private String jdbcURL = "jdbc:mysql://localhost:3306/demo?useSSL=false";

    /** Database user login */
    private String jdbcUsername = "root";

    /** Database user password */
    private String jdbcPassword = "";

    /** SQL statement to insert a new user */
    private static final String INSERT_USERS_SQL =
            "INSERT INTO users (name, email, country) VALUES (?, ?, ?);";

    /** SQL statement to select a user by their ID */
    private static final String SELECT_USER_BY_ID =
            "SELECT id, name, email, country FROM users WHERE id = ?;";

    /** SQL statement to select all users */
    private static final String SELECT_ALL_USERS =
            "SELECT * FROM users;";

    /** SQL statement to delete a user by their ID */
    private static final String DELETE_USERS_SQL =
            "DELETE FROM users WHERE id = ?;";

    /** SQL statement to update an existing user */
    private static final String UPDATE_USERS_SQL =
            "UPDATE users SET name = ?, email = ?, country = ? WHERE id = ?;";

    /**
     * Establishes and returns a new database connection.
     * This method explicitly loads the MySQL JDBC driver class to ensure compatibility
     * with environments where the driver is not auto-registered.
     * 
     * @return a fresh {@link Connection} instance to the database
     * @throws SQLException if a database access error occurs or the URL is invalid
     * @throws ClassNotFoundException if the MySQL JDBC driver class cannot be found
     */
    protected Connection getConnection() throws SQLException, ClassNotFoundException {
        Class.forName("com.mysql.cj.jdbc.Driver");
        return DriverManager.getConnection(jdbcURL, jdbcUsername, jdbcPassword);
    }

    /**
     * Persists a new User record in the database.
     * The user's ID is auto-generated by the database.
     * 
     * @param user the {@link User} instance containing the information to store; 
     *             the {@code id} field is ignored
     * @throws RuntimeException if a database error occurs during insertion
     */
    public void insertUser(User user) {
        try (Connection connection = getConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(INSERT_USERS_SQL)) {

            preparedStatement.setString(1, user.getName());
            preparedStatement.setString(2, user.getEmail());
            preparedStatement.setString(3, user.getCountry());

            preparedStatement.executeUpdate();
        } catch (SQLException | ClassNotFoundException e) {
            // Ideally, use a logging framework here
            e.printStackTrace();
            throw new RuntimeException("Error inserting user", e);
        }
    }

    /**
     * Updates an existing User record.
     * The user to update is identified by the {@code id} field of the {@code user} parameter.
     * 
     * @param user the {@link User} instance with updated fields and a valid id
     * @return {@code true} if the update was successful (at least one row affected);
     *         {@code false} if no user with the given ID exists
     * @throws RuntimeException if a database error occurs during update
     */
    public boolean updateUser(User user) {
        boolean rowUpdated = false;
        try (Connection connection = getConnection();
             PreparedStatement statement = connection.prepareStatement(UPDATE_USERS_SQL)) {

            statement.setString(1, user.getName());
            statement.setString(2, user.getEmail());
            statement.setString(3, user.getCountry());
            statement.setInt(4, user.getId());

            rowUpdated = statement.executeUpdate() > 0;
        } catch (SQLException | ClassNotFoundException e) {
            e.printStackTrace();
            throw new RuntimeException("Error updating user", e);
        }
        return rowUpdated;
    }

    /**
     * Retrieves a User by their unique identifier.
     * 
     * @param id the ID of the user to retrieve
     * @return a {@link User} object if found; {@code null} if no user matches the id
     * @throws RuntimeException if a database error occurs during the query
     */
    public User selectUser(int id) {
        User user = null;
        try (Connection connection = getConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(SELECT_USER_BY_ID)) {

            preparedStatement.setInt(1, id);
            ResultSet rs = preparedStatement.executeQuery();

            if (rs.next()) {
                String name = rs.getString("name");
                String email = rs.getString("email");
                String country = rs.getString("country");
                user = new User(id, name, email, country);
            }
        } catch (SQLException | ClassNotFoundException e) {
            e.printStackTrace();
            throw new RuntimeException("Error selecting user by ID", e);
        }
        return user;
    }

    /**
     * Retrieves all users from the database.
     * 
     * @return a {@link List} of {@link User} objects; empty list if no users found
     * @throws RuntimeException if a database error occurs during the query
     */
    public List<User> selectAllUsers() {
        List<User> users = new ArrayList<>();
        try (Connection connection = getConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(SELECT_ALL_USERS)) {

            ResultSet rs = preparedStatement.executeQuery();

            while (rs.next()) {
                int id = rs.getInt("id");
                String name = rs.getString("name");
                String email = rs.getString("email");
                String country = rs.getString("country");
                users.add(new User(id, name, email, country));
            }
        } catch (SQLException | ClassNotFoundException e) {
            e.printStackTrace();
            throw new RuntimeException("Error selecting all users", e);
        }
        return users;
    }

    /**
     * Deletes a user from the database by their ID.
     * 
     * @param id the ID of the user to delete
     * @return {@code true} if a user was deleted; {@code false} if no user matched the ID
     * @throws RuntimeException if a database error occurs during deletion
     */
    public boolean deleteUser(int id) {
        boolean rowDeleted = false;
        try (Connection connection = getConnection();
             PreparedStatement statement = connection.prepareStatement(DELETE_USERS_SQL)) {

            statement.setInt(1, id);
            rowDeleted = statement.executeUpdate() > 0;
        } catch (SQLException | ClassNotFoundException e) {
            e.printStackTrace();
            throw new RuntimeException("Error deleting user", e);
        }
        return rowDeleted;
    }
}
